on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: treebeardtech/treebeard@master
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-username: treebeardtech
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
          docker-image-name: treebeardtech/treebeard_demo
          notebooks: "Only run this notebook.ipynb"
        env: |
            TB_MY_CUSTOM_AUTH_TOKEN=${{ secrets.MY_CUSTOM_AUTH_TOKEN }}
            TB_MY_SECOND_CUSTOM_AUTH_TOKEN=${{ secrets.MY_SECOND_CUSTOM_AUTH_TOKEN }}
