on: push
jobs:
  run:
    runs-on: windows-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt # Manually install python deps as running dockerless
      - uses: treebeardtech/treebeard@master
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-username: treebeardtech
          docker-password: "${{ secrets.DOCKER_PASSWORD }}"
          docker-image-name: treebeardtech/treebeard_demo
          notebooks: "Windows test.ipynb"
        env:
          TB_MY_CUSTOM_AUTH_TOKEN: ${{ secrets.MY_CUSTOM_AUTH_TOKEN }}
