on: push
jobs:
  run:
    runs-on: windows-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt # Manually install python deps as running dockerless
      - uses: treebeardtech/treebeard@master
        with:
          use-docker: False
<<<<<<< HEAD
          notebooks: "windows_test.ipynb"
=======
          notebooks: "Windows test.ipynb"
          debug: true
>>>>>>> 4ff0c38bda4be79fed41d819cc8ff8e2ea6d1f27
        env:
          TB_MY_CUSTOM_AUTH_TOKEN: ${{ secrets.MY_CUSTOM_AUTH_TOKEN }}
